apiVersion: v2
name: simple-elasticsearch-cleaner
description: A Helm chart for Simple Elasticsearch Cleaner to create a cron job in Kubernetes to delete all indices and their associated data streams from the Elasticsearch cluster which are older than the specified number of days.
type: application
sources:
  - https://github.com/abdullahkhawer/simple-elasticsearch-cleaner/tree/master/helm-charts/simple-elasticsearch-cleaner
maintainers:
  - name: Abdullah Khawer
    email: abdullahkhawer@live.com
    url: https://github.com/abdullahkhawer
version: 1.1.0
appVersion: "2.1.0"
