apiVersion: v2
appVersion: 2.1.0
version: 1.1.0
name: simple-elasticsearch-cleaner
description: A Helm chart for Simple Elasticsearch Cleaner to create a cron job in Kubernetes to run it.
type: application
home: https://github.com/abdullahkhawer/simple-elasticsearch-cleaner
sources:
  - https://github.com/abdullahkhawer/simple-elasticsearch-cleaner/tree/master/helm-charts/simple-elasticsearch-cleaner
maintainers:
  - name: Abdullah Khawer
    email: abdullahkhawer@live.com
    url: https://github.com/abdullahkhawer
