apiVersion: v1
entries:
  simple-elasticsearch-cleaner:
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2024-12-13T17:08:06.301397+01:00"
    description: A Helm chart for Simple Elasticsearch Cleaner to create a cron job in Kubernetes to run it.
    digest: ?
    name: simple-elasticsearch-cleaner
    type: application
    urls:
    - https://abdullahkhawer.github.io/simple-elasticsearch-cleaner/charts/simple-elasticsearch-cleaner-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 2.0.0
    description: A Helm chart for Simple Elasticsearch Cleaner to create a cron job in Kubernetes to run it.
    digest: bba73328bc1253861a4edbad7e83888eaf8c3662d26a972bed19143bb3a52c25
    name: simple-elasticsearch-cleaner
    type: application
    urls:
    - https://abdullahkhawer.github.io/simple-elasticsearch-cleaner/charts/simple-elasticsearch-cleaner-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-13T17:08:06.301397+01:00"
